import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const base=process.env.QA_URL||'http://127.0.0.1:4173/PAINT-YOUR-LOGO-WALL/';
await fs.mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});
const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
const res=await page.goto(base,{waitUntil:'networkidle'});if(!res?.ok())throw new Error(`Page HTTP ${res?.status()}`);
await page.waitForFunction(()=>window.__PYLW__?.ready===true,{timeout:15000});
const initial=await page.evaluate(()=>({s:window.__PYLW__,panel:getComputedStyle(document.querySelector('#authoring-panel')),canvas:document.querySelector('#stage').getBoundingClientRect()}));
if(initial.s.jobs!==5)throw new Error(`Expected 5 jobs, got ${initial.s.jobs}`);if(!initial.s.cssLoaded)throw new Error('CSS did not load');if(initial.canvas.width<500||initial.canvas.height<500)throw new Error('Canvas not visible');
await page.selectOption('#crew-select','foxie');await page.waitForTimeout(250);const crew=await page.evaluate(()=>window.__PYLW__.crew);if(crew!=='foxie')throw new Error('Crew switch failed');
await page.$eval('#timeline',el=>{el.value=.11;el.dispatchEvent(new Event('input',{bubbles:true}))});await page.waitForTimeout(200);await page.$eval('#timeline',el=>{el.value=.16;el.dispatchEvent(new Event('input',{bubbles:true}))});await page.waitForTimeout(200);const paint=await page.evaluate(()=>window.__PYLW__);if(paint.paintProgress<=0)throw new Error(`Paint mask did not advance: ${paint.paintProgress}`);
await page.screenshot({path:'artifacts/v1-painting.png',fullPage:true});await page.click('[data-world="dark"]');await page.waitForTimeout(250);await page.screenshot({path:'artifacts/v1-dark-world.png',fullPage:true});
if(errors.length)throw new Error(`Browser errors: ${errors.join(' | ')}`);
await fs.writeFile('artifacts/qa.json',JSON.stringify({url:base,initial:initial.s,paint,errors},null,2));await browser.close();console.log('Paint Your Logo Wall V1 QA passed');