import * as THREE from 'three';
import './style.css';
import {CREW_TEMPLATES,createCrewRig,animateCrew} from './crew-library.js';

const $=s=>document.querySelector(s);const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;const ease=t=>t*t*(3-2*t);const STORAGE='paint-your-logo-wall-v1-project';
const state={playing:true,time:0,pace:1,crew:'aya',crewScale:1,motion:1,tool:'brush',brush:42,edge:.34,paintSpeed:1,wet:.22,world:'plaster',wall:'#d8cdbd',textureScale:1,light:3.2,exposure:1,shadows:true,camera:11,parallax:.08,selectedJob:0};
try{Object.assign(state,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}

const canvas=$('#stage');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=state.exposure;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc9beaf);scene.fog=new THREE.Fog(0xc9beaf,11,22);
const camera=new THREE.PerspectiveCamera(38,1,.1,60);camera.position.set(0,.25,state.camera);camera.lookAt(0,.3,0);
const hemi=new THREE.HemisphereLight(0xfff7e9,0x6d6255,1.35);scene.add(hemi);const key=new THREE.DirectionalLight(0xffe5c4,state.light);key.position.set(4.5,7.5,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=-8;key.shadow.camera.right=8;key.shadow.camera.top=7;key.shadow.camera.bottom=-5;scene.add(key);const rim=new THREE.DirectionalLight(0xb9d7ff,.75);rim.position.set(-6,3,4);scene.add(rim);

const wallMat=new THREE.MeshStandardMaterial({color:state.wall,roughness:.95,metalness:0});const wall=new THREE.Mesh(new THREE.PlaneGeometry(14,6.6,1,1),wallMat);wall.position.set(0,.8,-.55);wall.receiveShadow=true;scene.add(wall);
const baseboard=new THREE.Mesh(new THREE.BoxGeometry(14,.16,.18),new THREE.MeshStandardMaterial({color:0xb9ac9b,roughness:.82}));baseboard.position.set(0,-2.42,-.25);baseboard.receiveShadow=true;scene.add(baseboard);
const floorMat=new THREE.MeshStandardMaterial({color:0xb3a794,roughness:.92});const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,9),floorMat);floor.rotation.x=-Math.PI/2;floor.position.set(0,-2.5,2.2);floor.receiveShadow=true;scene.add(floor);

function mkCanvas(w=1024,h=512){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function demoAsset(i){const c=mkCanvas(),g=c.getContext('2d');g.clearRect(0,0,1024,512);const p=[['#17222e','#e05d49'],['#21372d','#d5a14c'],['#27232e','#efe7db'],['#163847','#ef815e'],['#4d2c29','#ead4a7']][i];g.fillStyle=p[0];if(i===0){g.font='700 132px Inter';g.fillText('NORTH',110,306);g.fillStyle=p[1];g.fillRect(115,342,520,22)}if(i===1){g.beginPath();g.arc(360,255,142,0,Math.PI*2);g.fill();g.fillStyle=p[1];g.beginPath();g.arc(635,255,96,0,Math.PI*2);g.fill()}if(i===2){[185,335,485,635].forEach((x,n)=>g.fillRect(x,110+n*25,82,275-n*28));g.fillStyle=p[1];g.fillRect(785,185,52,205)}if(i===3){g.font='700 168px Georgia';g.fillText('S',275,338);g.fillStyle=p[1];g.font='600 70px Inter';g.fillText('STUDIO',430,306)}if(i===4){g.strokeStyle=p[0];g.lineWidth=48;g.beginPath();g.moveTo(170,330);g.lineTo(330,150);g.lineTo(490,330);g.lineTo(650,150);g.lineTo(820,330);g.stroke();g.fillStyle=p[1];g.beginPath();g.arc(490,330,43,0,Math.PI*2);g.fill()}return c}
function makeJob(i,x,y){const source=demoAsset(i),mask=mkCanvas(),out=mkCanvas(),temp=mkCanvas();const tex=new THREE.CanvasTexture(out);tex.colorSpace=THREE.SRGBColorSpace;tex.minFilter=THREE.LinearFilter;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(2.1,1.05),new THREE.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false}));mesh.position.set(x,y,-.16);scene.add(mesh);return{id:i,name:['North','Field','Mono','Studio','Signal'][i],x,y,baseY:y,scale:1,source,mask,out,temp,texture:tex,mesh,progress:0,uploadName:null}}
const jobs=[makeJob(0,-4.7,.95),makeJob(1,-2.35,1.38),makeJob(2,0,.88),makeJob(3,2.35,1.4),makeJob(4,4.7,.96)];
function paint(job,p){p=clamp(p);job.progress=p;const m=job.mask.getContext('2d');m.clearRect(0,0,1024,512);m.strokeStyle='#fff';m.lineCap=state.tool==='roller'?'butt':'round';m.lineJoin='round';m.lineWidth=state.brush*(state.tool==='roller'?3.5:2.2);const rows=state.tool==='roller'?6:9,full=p*rows;for(let r=0;r<Math.ceil(full);r++){const f=clamp(full-r),rev=r%2===1,y=(r+.5)/rows*512;const jitter=Math.sin((r+1)*12.73)*state.edge*15;m.beginPath();m.moveTo(rev?960:64,y+jitter);m.lineTo(lerp(rev?960:64,rev?64:960,f),y-jitter*.3);m.stroke()}const t=job.temp.getContext('2d');t.clearRect(0,0,1024,512);t.drawImage(job.source,0,0,1024,512);t.globalCompositeOperation='destination-in';t.drawImage(job.mask,0,0);t.globalCompositeOperation='source-over';const o=job.out.getContext('2d');o.clearRect(0,0,1024,512);o.globalAlpha=.86+state.wet*.14;o.drawImage(job.temp,0,0);o.globalAlpha=1;job.texture.needsUpdate=true}
jobs.forEach(j=>paint(j,0));

let crewRig=null,crewKey='';function rebuildCrew(){if(crewRig)scene.remove(crewRig.root);crewKey=state.crew;crewRig=createCrewRig(CREW_TEMPLATES[crewKey]);crewRig.root.scale.setScalar(.64*state.crewScale);scene.add(crewRig.root)}rebuildCrew();
const ladder=new THREE.Group();const ladderMat=new THREE.MeshStandardMaterial({color:0x8f7d67,roughness:.5,metalness:.2});for(const x of [-.34,.34]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.09,2.8,.09),ladderMat);rail.position.x=x;rail.rotation.z=x<0?-.08:.08;rail.castShadow=true;ladder.add(rail)}for(let y=-1.08;y<1.18;y+=.38){const rung=new THREE.Mesh(new THREE.BoxGeometry(.64,.055,.07),ladderMat);rung.position.y=y;rung.castShadow=true;ladder.add(rung)}scene.add(ladder);
const canGroup=new THREE.Group();const canMat=new THREE.MeshStandardMaterial({color:0xd4a15d,roughness:.45,metalness:.25});const can=new THREE.Mesh(new THREE.CylinderGeometry(.13,.13,.27,18),canMat);can.castShadow=true;canGroup.add(can);scene.add(canGroup);

const JOB_DURATION=8,TOTAL=JOB_DURATION*jobs.length;const phases=[['walking to job',0,.13],['positioning ladder',.13,.23],['climbing',.23,.35],['preparing tool',.35,.42],['painting',.42,.83],['inspecting',.83,.9],['descending',.9,.97],['moving to next job',.97,1]];const phaseAt=p=>phases.find(x=>p>=x[1]&&p<x[2])||phases.at(-1);
let last=performance.now();let baseCrewY=-2.0;
function updateStory(){const t=clamp(state.time,0,TOTAL-.001),idx=Math.min(4,Math.floor(t/JOB_DURATION)),job=jobs[idx],p=(t-idx*JOB_DURATION)/JOB_DURATION,phase=phaseAt(p)[0];jobs.forEach((j,i)=>paint(j,i<idx?1:i>idx?0:clamp((p-.42)/(.83-.42)*state.paintSpeed)));const prev=idx===0?-6.0:jobs[idx-1].x,target=job.x-.68,walk=ease(clamp(p/.13));crewRig.root.position.x=lerp(prev-.7,target,walk);ladder.position.x=lerp(prev-.1,job.x-.08,ease(clamp((p-.08)/.15)));const climb=p<.23?0:p<.35?ease((p-.23)/.12):p<.9?1:p<.97?1-ease((p-.9)/.07):0;baseCrewY=-2.0+climb*.5;crewRig.root.position.y=baseCrewY;crewRig.root.scale.setScalar(.64*state.crewScale);ladder.position.y=-1.08;canGroup.position.set(job.x-.8,-2.28,.18);crewRig.toolPivot.visible=phase==='preparing tool'||phase==='painting';animateCrew(crewRig,{phase,progress:clamp((p-.42)/.41),time:t,motion:state.motion});$('#job-chip').textContent=`JOB ${String(idx+1).padStart(2,'0')} · ${job.name.toUpperCase()} · ${phase.toUpperCase()}`;$('#activity').textContent=phase;$('#clock').textContent=`00:${String(Math.floor(t)).padStart(2,'0')}`;$('#timeline').value=t/TOTAL;window.__PYLW__={ready:true,jobIndex:idx,phase,paintProgress:job.progress,crew:state.crew,jobs:jobs.length,cssLoaded:getComputedStyle($('#authoring-panel')).backgroundColor!=='rgba(0, 0, 0, 0)'}}

function world(name){state.world=name;document.body.classList.toggle('world-dark',name==='dark');const cfg={plaster:[0xd8cdbd,0xb4a691,0xc9beaf],concrete:[0xaaa9a3,0x8f8d86,0xb6b4ae],white:[0xeeeae2,0xd8d4cd,0xf0ede8],dark:[0x3a3938,0x272625,0x343332],mediterranean:[0xd9c9a9,0xbca77e,0xe1d2b7],brick:[0x9b6c59,0x715043,0xaa7a64]}[name];wallMat.color.set(cfg[0]);floorMat.color.set(cfg[1]);scene.background.set(cfg[2]);scene.fog.color.set(cfg[2]);state.wall='#'+wallMat.color.getHexString();$('#wall-color').value=state.wall;$('#world-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.world===name));persist()}
function lighting(name){const c={studio:[3.2,1.35,0xffe5c4],golden:[4.2,1.0,0xffc477],overcast:[1.7,1.8,0xe8edf2],dramatic:[5.1,.55,0xffd0a0]}[name];key.intensity=c[0];hemi.intensity=c[1];key.color.set(c[2]);state.light=c[0];$('#light').value=c[0];$('#out-light').value=c[0].toFixed(2);$('#light-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.light===name));persist()}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(state));$('#status').textContent='Project saved locally'}function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1700)}

$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'PAUSE':'PLAY'};$('#restart').onclick=()=>{state.time=0;state.playing=true;$('#play').textContent='PAUSE'};$('#pace').onchange=e=>state.pace=+e.target.value;$('#timeline').oninput=e=>{state.time=+e.target.value*TOTAL;state.playing=false;$('#play').textContent='PLAY';updateStory()};$('#crew-select').value=state.crew;$('#crew-select').onchange=e=>{state.crew=e.target.value;rebuildCrew();persist();toast(CREW_TEMPLATES[state.crew].name)};
function bindRange(id,key,out,fmt=v=>Number(v).toFixed(2),after=()=>{}){const el=$(id),o=$(out);el.value=state[key];o.value=fmt(state[key]);el.oninput=e=>{state[key]=+e.target.value;o.value=fmt(state[key]);after();persist()}}
bindRange('#crew-scale','crewScale','#out-crew-scale');bindRange('#motion','motion','#out-motion');bindRange('#brush-size','brush','#out-brush',v=>String(Math.round(v)));bindRange('#edge-texture','edge','#out-edge');bindRange('#paint-speed','paintSpeed','#out-paint-speed');bindRange('#wet','wet','#out-wet');bindRange('#texture-scale','textureScale','#out-texture');bindRange('#light','light','#out-light',v=>Number(v).toFixed(2),()=>key.intensity=state.light);bindRange('#exposure','exposure','#out-exposure',v=>Number(v).toFixed(2),()=>renderer.toneMappingExposure=state.exposure);bindRange('#camera-distance','camera','#out-camera',v=>Number(v).toFixed(1),()=>camera.position.z=state.camera);bindRange('#parallax','parallax','#out-parallax');
$('#tool').value=state.tool;$('#tool').onchange=e=>{state.tool=e.target.value;persist()};$('#wall-color').value=state.wall;$('#wall-color').oninput=e=>{state.wall=e.target.value;wallMat.color.set(state.wall);persist()};$('#shadows').checked=state.shadows;$('#shadows').onchange=e=>{state.shadows=e.target.checked;renderer.shadowMap.enabled=state.shadows;persist()};$('#world-presets').onclick=e=>{if(e.target.dataset.world)world(e.target.dataset.world)};$('#light-presets').onclick=e=>{if(e.target.dataset.light)lighting(e.target.dataset.light)};
$('#job-select').onchange=e=>{state.selectedJob=+e.target.value;$('#selected-item-label').textContent=`Job ${String(state.selectedJob+1).padStart(2,'0')}`};bindRange('#logo-scale','_dummyLogo','#out-logo-scale',v=>Number(v).toFixed(2),()=>{});state._dummyLogo=1;$('#logo-scale').value=1;$('#logo-scale').oninput=e=>{const j=jobs[state.selectedJob];j.scale=+e.target.value;j.mesh.scale.setScalar(j.scale);$('#out-logo-scale').value=j.scale.toFixed(2)};$('#job-height').oninput=e=>{const j=jobs[state.selectedJob];j.mesh.position.y=j.baseY+(+e.target.value);$('#out-job-height').value=(+e.target.value).toFixed(2)};
$('#asset-upload').onchange=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const j=jobs[state.selectedJob],g=j.source.getContext('2d');g.clearRect(0,0,1024,512);const s=Math.min(1024/img.width,512/img.height),w=img.width*s,h=img.height*s;g.drawImage(img,(1024-w)/2,(512-h)/2,w,h);j.uploadName=file.name;paint(j,j.progress);$('#asset-status').textContent=`${file.name} · image pipeline ready`;toast('Logo / image loaded')};img.src=reader.result};reader.readAsDataURL(file);e.target.value=''};
$('#save-project').onclick=()=>persist();$('#reset-project').onclick=()=>{localStorage.removeItem(STORAGE);location.reload()};$('#capture').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='paint-your-logo-wall.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};

function resize(){const box=$('#stage-shell').getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
let mx=0,my=0;$('#stage-shell').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect();mx=(e.clientX/r.width-.5)*2;my=(e.clientY/r.height-.5)*2});
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing){state.time+=dt*state.pace;if(state.time>=TOTAL)state.time=0}updateStory();camera.position.x=mx*state.parallax;camera.position.y=.25-my*state.parallax*.4;camera.lookAt(0,.25,0);renderer.render(scene,camera)}
world(state.world);updateStory();resize();setTimeout(()=>$('#loading').classList.add('hidden'),350);requestAnimationFrame(frame);