import * as THREE from 'three';
import {CREW_TEMPLATES,createCrewRig,animateCrew} from './crew-library.js';
import {JobManager,METHODS,demoCanvas} from './v2-jobs.js';
const $=s=>document.querySelector(s),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t),STORAGE='paint-your-logo-wall-v2-project';
export function bootV2(){
const state={playing:false,time:0,pace:1,crew:'aya',crewScale:1,motion:1,brush:42,edge:.34,paintSpeed:1,wet:.22,world:'plaster',wall:'#d8cdbd',light:3.2,exposure:1,shadows:true,camera:11,parallax:.08,selected:0};try{Object.assign(state,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}
const canvas=$('#stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=state.exposure;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc9beaf);scene.fog=new THREE.Fog(0xc9beaf,11,22);const camera=new THREE.PerspectiveCamera(38,1,.1,60);camera.position.set(0,.25,state.camera);camera.lookAt(0,.3,0);const hemi=new THREE.HemisphereLight(0xfff7e9,0x6d6255,1.35);scene.add(hemi);const key=new THREE.DirectionalLight(0xffe5c4,state.light);key.position.set(4.5,7.5,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0xb9d7ff,.75);rim.position.set(-6,3,4);scene.add(rim);
const wallMat=new THREE.MeshStandardMaterial({color:state.wall,roughness:.95});const wall=new THREE.Mesh(new THREE.PlaneGeometry(14,6.6),wallMat);wall.position.set(0,.8,-.55);wall.receiveShadow=true;scene.add(wall);const floorMat=new THREE.MeshStandardMaterial({color:0xb3a794,roughness:.92});const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,9),floorMat);floor.rotation.x=-Math.PI/2;floor.position.set(0,-2.5,2.2);floor.receiveShadow=true;scene.add(floor);const baseboard=new THREE.Mesh(new THREE.BoxGeometry(14,.16,.18),new THREE.MeshStandardMaterial({color:0xb9ac9b,roughness:.82}));baseboard.position.set(0,-2.42,-.25);scene.add(baseboard);
const manager=new JobManager(scene);let crewRig=null;function rebuildCrew(){if(crewRig)scene.remove(crewRig.root);crewRig=createCrewRig(CREW_TEMPLATES[state.crew]);crewRig.root.scale.setScalar(.64*state.crewScale);scene.add(crewRig.root)}rebuildCrew();
const ladder=new THREE.Group(),ladderMat=new THREE.MeshStandardMaterial({color:0x8f7d67,roughness:.5,metalness:.2});for(const x of [-.34,.34]){const r=new THREE.Mesh(new THREE.BoxGeometry(.09,2.8,.09),ladderMat);r.position.x=x;r.rotation.z=x<0?-.08:.08;ladder.add(r)}for(let y=-1.08;y<1.18;y+=.38){const r=new THREE.Mesh(new THREE.BoxGeometry(.64,.055,.07),ladderMat);r.position.y=y;ladder.add(r)}scene.add(ladder);
const phases=[['walking to job',0,.13],['positioning ladder',.13,.23],['climbing',.23,.35],['preparing tool',.35,.42],['creating',.42,.83],['inspecting',.83,.9],['descending',.9,.97],['moving to next job',.97,1]],phaseAt=p=>phases.find(x=>p>=x[1]&&p<x[2])?.[0]||'moving to next job';
function persist(){localStorage.setItem(STORAGE,JSON.stringify({...state,time:0,playing:false}));$('#status').textContent='Project settings saved locally'}function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
function renderJobs(){const list=$('#job-list');list.innerHTML='';manager.jobs.forEach((j,i)=>{const row=document.createElement('div');row.className='job-row'+(i===state.selected?' active':'');row.innerHTML=`<span class="job-index">${String(i+1).padStart(2,'0')}</span><div class="job-meta"><b>${j.name}</b><span>${j.type} · ${j.method} · ${j.reveal}</span></div><div class="job-actions"><button data-up>↑</button><button data-down>↓</button></div>`;row.onclick=e=>{if(e.target.dataset.up!==undefined){e.stopPropagation();state.selected=manager.move(i,-1);renderJobs();syncJob();return}if(e.target.dataset.down!==undefined){e.stopPropagation();state.selected=manager.move(i,1);renderJobs();syncJob();return}state.selected=i;renderJobs();syncJob()};list.appendChild(row)});$('#job-count').textContent=`${manager.jobs.length} Job${manager.jobs.length===1?'':'s'}`;$('#asset-status').textContent=manager.jobs.length?`${manager.jobs.length} jobs · ${manager.jobs.filter(j=>j.type==='video').length} video · ${manager.jobs.filter(j=>j.type==='image').length} image`:'Upload content to begin. Images and videos share one asset pipeline.'}
function syncJob(){const j=manager.jobs[state.selected],set=(id,v,out,txt)=>{$(id).disabled=!j;if(j)$(id).value=v;if(j&&out)$(out).value=txt??v};$('#selected-item-label').textContent=j?`Job ${String(state.selected+1).padStart(2,'0')}`:'None';set('#job-scale',j?.scale,'#out-job-scale',j?.scale.toFixed(2));set('#job-height',j?.height,'#out-job-height',j?.height.toFixed(2));set('#job-rotation',j?.rotation,'#out-job-rotation',j?`${j.rotation}°`:null);set('#job-duration',j?.duration,'#out-duration',j?`${j.duration.toFixed(1)}s`:null);set('#asset-fit',j?.fit);set('#reveal-mask',j?.reveal);$('#living-video').disabled=!j;$('#living-video').checked=!!j?.living;$('#method-grid').querySelectorAll('button').forEach(b=>b.classList.toggle('active',j?.method===b.dataset.method))}
function recalc(){state.time=clamp(state.time,0,manager.totalDuration()-.001)}
async function ingest(files){for(const f of files)await manager.fromFile(f);state.selected=Math.max(0,manager.jobs.length-files.length);$('#onboarding').classList.add('hidden');recalc();renderJobs();syncJob();toast(`${files.length} asset${files.length>1?'s':''} added`)}
function addDemo(n=5){for(let i=0;i<n;i++)manager.create({name:['North','Field','Mono','Studio','Signal'][i%5],source:demoCanvas(i)});$('#onboarding').classList.add('hidden');recalc();renderJobs();syncJob()}
function updateStory(){const jobs=manager.jobs,total=manager.totalDuration();if(!jobs.length){$('#job-chip').textContent='WAITING FOR CONTENT';$('#activity').textContent='waiting';window.__PYLW_V2__={ready:true,jobs:0,cssLoaded:true,videoJobs:0};return}const {i,local:p}=manager.resolveTime(clamp(state.time,0,total-.001)),job=jobs[i],phase=phaseAt(p);jobs.forEach((j,n)=>manager.paint(j,n<i?1:n>i?0:clamp((p-.42)/.41*state.paintSpeed),{size:state.brush,edge:state.edge,wet:state.wet}));const prev=i===0?-6:jobs[i-1].x,target=job.x-.68;crewRig.root.position.x=lerp(prev-.7,target,ease(clamp(p/.13)));ladder.position.x=lerp(prev-.1,job.x-.08,ease(clamp((p-.08)/.15)));const climb=p<.23?0:p<.35?ease((p-.23)/.12):p<.9?1:p<.97?1-ease((p-.9)/.07):0;crewRig.root.position.y=-2+climb*.5;crewRig.root.scale.setScalar(.64*state.crewScale);ladder.position.y=-1.08;crewRig.toolPivot.visible=phase==='preparing tool'||phase==='creating';animateCrew(crewRig,{phase:phase==='creating'?'painting':phase,progress:clamp((p-.42)/.41),time:state.time,motion:state.motion});$('#job-chip').textContent=`JOB ${String(i+1).padStart(2,'0')} · ${job.name.toUpperCase()} · ${job.method.toUpperCase()} · ${phase.toUpperCase()}`;$('#activity').textContent=phase;$('#clock').textContent=`00:${String(Math.floor(state.time)).padStart(2,'0')}`;$('#timeline').value=state.time/total;if(job.type==='video'&&job.media){if(job.living&&job.progress>.02)job.media.play().catch(()=>{});else job.media.pause()}window.__PYLW_V2__={ready:true,jobs:jobs.length,jobIndex:i,phase,method:job.method,reveal:job.reveal,paintProgress:job.progress,cssLoaded:getComputedStyle($('#authoring-panel')).backgroundColor!=='rgba(0, 0, 0, 0)',videoJobs:jobs.filter(j=>j.type==='video').length}}
function world(name){state.world=name;document.body.classList.toggle('world-dark',name==='dark');const c={plaster:[0xd8cdbd,0xb4a691,0xc9beaf],concrete:[0xaaa9a3,0x8f8d86,0xb6b4ae],white:[0xeeeae2,0xd8d4cd,0xf0ede8],dark:[0x3a3938,0x272625,0x343332],mediterranean:[0xd9c9a9,0xbca77e,0xe1d2b7],brick:[0x9b6c59,0x715043,0xaa7a64]}[name];wallMat.color.set(c[0]);floorMat.color.set(c[1]);scene.background.set(c[2]);scene.fog.color.set(c[2]);state.wall='#'+wallMat.color.getHexString();$('#wall-color').value=state.wall;$('#world-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.world===name));persist()}
function lighting(name){const c={studio:[3.2,1.35,0xffe5c4],golden:[4.2,1,0xffc477],overcast:[1.7,1.8,0xe8edf2],dramatic:[5.1,.55,0xffd0a0]}[name];key.intensity=c[0];hemi.intensity=c[1];key.color.set(c[2]);state.light=c[0];$('#light').value=c[0];$('#out-light').value=c[0].toFixed(2);$('#light-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.light===name));persist()}
$('#asset-upload').onchange=async e=>{const f=[...e.target.files];if(f.length)await ingest(f);e.target.value=''};$('#use-demo').onclick=()=>addDemo(5);$('#add-demo-job').onclick=()=>{manager.create({name:`Demo ${manager.jobs.length+1}`,source:demoCanvas(manager.jobs.length)});$('#onboarding').classList.add('hidden');recalc();renderJobs();syncJob()};$('#duplicate-job').onclick=()=>{if(manager.duplicate(state.selected)){state.selected=manager.jobs.length-1;recalc();renderJobs();syncJob()}};$('#delete-job').onclick=()=>{manager.delete(state.selected);state.selected=clamp(state.selected,0,Math.max(0,manager.jobs.length-1));recalc();renderJobs();syncJob()};
$('#method-grid').onclick=e=>{const b=e.target.closest('button[data-method]'),j=manager.jobs[state.selected];if(!b||!j)return;j.method=b.dataset.method;j.reveal=METHODS[j.method].reveal;state.crew=METHODS[j.method].crew;$('#crew-select').value=state.crew;rebuildCrew();renderJobs();syncJob();toast(`${METHODS[j.method].label} method`)};$('#reveal-mask').onchange=e=>{const j=manager.jobs[state.selected];if(j){j.reveal=e.target.value;renderJobs()}};
const jobBind=(id,key,out,fmt,after)=>$(id).oninput=e=>{const j=manager.jobs[state.selected];if(!j)return;j[key]=e.target.valueAsNumber;$(out).value=fmt(j[key]);after?.(j);renderJobs()};jobBind('#job-scale','scale','#out-job-scale',v=>v.toFixed(2),j=>j.mesh.scale.setScalar(j.scale));jobBind('#job-height','height','#out-job-height',v=>v.toFixed(2),j=>j.mesh.position.y=j.baseY+j.height);jobBind('#job-rotation','rotation','#out-job-rotation',v=>`${Math.round(v)}°`,j=>j.mesh.rotation.z=THREE.MathUtils.degToRad(j.rotation));jobBind('#job-duration','duration','#out-duration',v=>`${v.toFixed(1)}s`,()=>recalc());$('#asset-fit').onchange=e=>{const j=manager.jobs[state.selected];if(j)j.fit=e.target.value};$('#living-video').onchange=e=>{const j=manager.jobs[state.selected];if(j)j.living=e.target.checked};
$('#play').onclick=()=>{if(!manager.jobs.length)return toast('Upload content first');state.playing=!state.playing;$('#play').textContent=state.playing?'PAUSE':'PLAY'};$('#restart').onclick=()=>{state.time=0;state.playing=false;$('#play').textContent='PLAY';updateStory()};$('#pace').onchange=e=>state.pace=+e.target.value;$('#timeline').oninput=e=>{state.time=+e.target.value*manager.totalDuration();state.playing=false;$('#play').textContent='PLAY';updateStory()};$('#crew-select').value=state.crew;$('#crew-select').onchange=e=>{state.crew=e.target.value;rebuildCrew();persist()};
function bindRange(id,keyName,out,fmt=v=>Number(v).toFixed(2),after=()=>{}){const el=$(id),o=$(out);el.value=state[keyName];o.value=fmt(state[keyName]);el.oninput=e=>{state[keyName]=+e.target.value;o.value=fmt(state[keyName]);after();persist()}}bindRange('#crew-scale','crewScale','#out-crew-scale');bindRange('#motion','motion','#out-motion');bindRange('#brush-size','brush','#out-brush',v=>String(Math.round(v)));bindRange('#edge-texture','edge','#out-edge');bindRange('#paint-speed','paintSpeed','#out-paint-speed');bindRange('#wet','wet','#out-wet');bindRange('#light','light','#out-light',v=>Number(v).toFixed(2),()=>key.intensity=state.light);bindRange('#exposure','exposure','#out-exposure',v=>Number(v).toFixed(2),()=>renderer.toneMappingExposure=state.exposure);bindRange('#camera-distance','camera','#out-camera',v=>Number(v).toFixed(1),()=>camera.position.z=state.camera);bindRange('#parallax','parallax','#out-parallax');$('#wall-color').value=state.wall;$('#wall-color').oninput=e=>{state.wall=e.target.value;wallMat.color.set(state.wall);persist()};$('#shadows').checked=state.shadows;$('#shadows').onchange=e=>{state.shadows=e.target.checked;renderer.shadowMap.enabled=state.shadows};$('#world-presets').onclick=e=>e.target.dataset.world&&world(e.target.dataset.world);$('#light-presets').onclick=e=>e.target.dataset.light&&lighting(e.target.dataset.light);$('#save-project').onclick=persist;$('#reset-project').onclick=()=>{localStorage.removeItem(STORAGE);location.reload()};$('#capture').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='paint-your-logo-wall-v2.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};
function resize(){const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas.parentElement);resize();world(state.world);lighting('studio');renderJobs();syncJob();setTimeout(()=>$('#loading').classList.add('hidden'),350);let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing&&manager.jobs.length){state.time+=dt*state.pace;if(state.time>=manager.totalDuration()){state.time=manager.totalDuration()-.001;state.playing=false;$('#play').textContent='PLAY'}}updateStory();renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);return{manager,state,renderer,scene};
}
