import * as THREE from 'three';
import {CREW_TEMPLATES,createCrewRig,animateCrew} from './crew-library.js';
import {JobManager,METHODS,demoCanvas} from './v2-jobs.js';
import {STYLE_PROFILES,narrativeBeat,toolPoint} from './v21-style-engine.js';
import {attachTool,animateTool} from './v21-tools.js';
const $=s=>document.querySelector(s),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t),STORAGE='paint-your-logo-wall-v21-project';

export function bootV21(){
const state={playing:false,time:0,pace:1,crew:'aya',crewScale:1,motion:1,brush:42,edge:.45,paintSpeed:1,wet:.3,world:'plaster',wall:'#d8cdbd',light:3.2,exposure:1,shadows:true,camera:11,parallax:.08,selected:0,layout:'gallery',bgOpacity:1,bgBlur:0,worldMotion:.08};try{Object.assign(state,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}
const canvas=$('#stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=state.exposure;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc9beaf);scene.fog=new THREE.Fog(0xc9beaf,11,24);const camera=new THREE.PerspectiveCamera(38,1,.1,60);camera.position.set(0,.25,state.camera);camera.lookAt(0,.3,0);
const hemi=new THREE.HemisphereLight(0xfff7e9,0x6d6255,1.35);scene.add(hemi);const key=new THREE.DirectionalLight(0xffe5c4,state.light);key.position.set(4.5,7.5,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0xb9d7ff,.75);rim.position.set(-6,3,4);scene.add(rim);
const wallMat=new THREE.MeshStandardMaterial({color:state.wall,roughness:.95,transparent:true,opacity:.96});const wall=new THREE.Mesh(new THREE.PlaneGeometry(14,6.6),wallMat);wall.position.set(0,.8,-.55);wall.receiveShadow=true;scene.add(wall);const floorMat=new THREE.MeshStandardMaterial({color:0xb3a794,roughness:.92});const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,9),floorMat);floor.rotation.x=-Math.PI/2;floor.position.set(0,-2.5,2.2);floor.receiveShadow=true;scene.add(floor);const baseboard=new THREE.Mesh(new THREE.BoxGeometry(14,.16,.18),new THREE.MeshStandardMaterial({color:0xb9ac9b,roughness:.82}));baseboard.position.set(0,-2.42,-.25);scene.add(baseboard);
const manager=new JobManager(scene);manager.layoutMode=state.layout;
let crewRig=null,currentTool=null,currentToolName='';function rebuildCrew(){if(crewRig)scene.remove(crewRig.root);crewRig=createCrewRig(CREW_TEMPLATES[state.crew]);crewRig.root.scale.setScalar(.64*state.crewScale);scene.add(crewRig.root);currentTool=null;currentToolName=''}rebuildCrew();
const ladder=new THREE.Group(),ladderMat=new THREE.MeshStandardMaterial({color:0x8f7d67,roughness:.5,metalness:.2});for(const x of [-.34,.34]){const r=new THREE.Mesh(new THREE.BoxGeometry(.09,2.8,.09),ladderMat);r.position.x=x;r.rotation.z=x<0?-.08:.08;r.castShadow=true;ladder.add(r)}for(let y=-1.08;y<1.18;y+=.38){const r=new THREE.Mesh(new THREE.BoxGeometry(.64,.055,.07),ladderMat);r.position.y=y;r.castShadow=true;ladder.add(r)}scene.add(ladder);
const fxGroup=new THREE.Group();scene.add(fxGroup);const fxGeo=new THREE.SphereGeometry(.012,6,4),fxMat=new THREE.MeshBasicMaterial({color:0xffe2a6,transparent:true,opacity:.7});for(let i=0;i<45;i++){const p=new THREE.Mesh(fxGeo,fxMat.clone());p.visible=false;fxGroup.add(p)}
let customBg=null,customBgMedia=null;function clearBg(){if(customBg?.isTexture)customBg.dispose();if(customBgMedia?.tagName==='VIDEO'){customBgMedia.pause();URL.revokeObjectURL(customBgMedia.src)}customBg=null;customBgMedia=null}
async function setBackgroundFile(file){clearBg();if(file.type.startsWith('video/')){const v=document.createElement('video');v.muted=true;v.loop=true;v.playsInline=true;v.autoplay=true;v.src=URL.createObjectURL(file);await v.play().catch(()=>{});customBgMedia=v;customBg=new THREE.VideoTexture(v);customBg.colorSpace=THREE.SRGBColorSpace}else{const img=new Image();img.src=URL.createObjectURL(file);await img.decode();customBg=new THREE.Texture(img);customBg.needsUpdate=true;customBg.colorSpace=THREE.SRGBColorSpace;URL.revokeObjectURL(img.src)}scene.background=customBg;scene.fog=null;$('#background-status').textContent=`${file.name} · custom world active`}

const phases=[['approaching',0,.1],['positioning ladder',.1,.19],['climbing',.19,.29],['preparing tool',.29,.37],['creating',.37,.79],['finishing',.79,.86],['inspecting',.86,.93],['activating artwork',.93,.97],['moving on',.97,1]],phaseAt=p=>phases.find(x=>p>=x[1]&&p<x[2])?.[0]||'moving on';
function persist(){localStorage.setItem(STORAGE,JSON.stringify({...state,time:0,playing:false}));$('#status').textContent='V2.1 project settings saved'}function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
function renderJobs(){const list=$('#job-list');list.innerHTML='';manager.jobs.forEach((j,i)=>{const row=document.createElement('div');row.className='job-row'+(i===state.selected?' active':'');row.innerHTML=`<span class="job-index">${String(i+1).padStart(2,'0')}</span><div class="job-meta"><b>${j.name}</b><span>${j.type} · ${METHODS[j.method].label}</span></div><div class="job-actions"><button data-up>↑</button><button data-down>↓</button></div>`;row.onclick=e=>{if(e.target.dataset.up!==undefined){e.stopPropagation();state.selected=manager.move(i,-1);renderJobs();syncJob();return}if(e.target.dataset.down!==undefined){e.stopPropagation();state.selected=manager.move(i,1);renderJobs();syncJob();return}state.selected=i;renderJobs();syncJob()};list.appendChild(row)});$('#job-count').textContent=`${manager.jobs.length} Job${manager.jobs.length===1?'':'s'}`;$('#asset-status').textContent=manager.jobs.length?`${manager.jobs.length} jobs · ${manager.jobs.filter(j=>j.type==='video').length} video · ${manager.jobs.filter(j=>j.type==='image').length} image`:'Upload content first. Every asset becomes a configurable creative job.'}
function syncJob(){const j=manager.jobs[state.selected],set=(id,v,out,txt)=>{if(!$(id))return;$(id).disabled=!j;if(j)$(id).value=v;if(j&&out)$(out).value=txt??v};$('#selected-item-label').textContent=j?`Job ${String(state.selected+1).padStart(2,'0')}`:'None';set('#job-scale',j?.scale,'#out-job-scale',j?.scale?.toFixed(2));set('#job-x',j?.xOffset,'#out-job-x',j?.xOffset?.toFixed(2));set('#job-height',j?.height,'#out-job-height',j?.height?.toFixed(2));set('#job-rotation',j?.rotation,'#out-job-rotation',j?`${j.rotation}°`:null);set('#job-duration',j?.duration,'#out-duration',j?`${j.duration.toFixed(1)}s`:null);set('#asset-fit',j?.fit);$('#living-video').disabled=!j;$('#living-video').checked=!!j?.living;$('#method-grid').querySelectorAll('button').forEach(b=>b.classList.toggle('active',j?.method===b.dataset.method));$('#style-summary').textContent=j?`${METHODS[j.method].label} · ${METHODS[j.method].narrative.join(' → ')}`:'Select a job'}
function recalc(){state.time=clamp(state.time,0,Math.max(.001,manager.totalDuration()-.001))}
async function ingest(files){for(const f of files)await manager.fromFile(f);state.selected=Math.max(0,manager.jobs.length-files.length);$('#onboarding').classList.add('hidden');recalc();renderJobs();syncJob();toast(`${files.length} asset${files.length>1?'s':''} added`)}
function addDemo(n=5){for(let i=0;i<n;i++){const j=manager.create({name:['North','Field','Mono','Studio','Signal'][i%5],source:demoCanvas(i)});j.method=['brush','spray','ink','expressionist','digital'][i%5];j.reveal=METHODS[j.method].reveal}$('#onboarding').classList.add('hidden');manager.layout(state.layout);recalc();renderJobs();syncJob()}
function ensureTool(method){const name=METHODS[method]?.tool||'brush';if(name!==currentToolName){currentToolName=name;currentTool=attachTool(crewRig.toolPivot,name)}}
function animateFX(job,phase,createP){fxGroup.children.forEach(p=>p.visible=false);if(phase!=='creating')return;if(!['spray','expressionist','charcoal','digital'].includes(job.method))return;const amount=job.method==='spray'?28:job.method==='expressionist'?18:10;for(let i=0;i<amount;i++){const p=fxGroup.children[i],r=(i*17.17+state.time*24)%1,a=i*2.399;p.visible=true;p.material.color.set(job.method==='digital'?0x73caff:job.method==='charcoal'?0x4a4540:0xffb05c);p.position.set(job.x-.15+Math.cos(a)*r*.48,job.mesh.position.y+Math.sin(a)*r*.28+.1,0.02+r*.2);p.scale.setScalar(.5+r*1.6);p.material.opacity=.25+(1-r)*.55}}
function updateStory(){const jobs=manager.jobs,total=manager.totalDuration();if(!jobs.length){$('#job-chip').textContent='WAITING FOR CONTENT';$('#activity').textContent='upload content';$('#narrative-beat').textContent='STEP 01 · Upload images or videos';window.__PYLW_V21__={ready:true,jobs:0,cssLoaded:true,styles:Object.keys(STYLE_PROFILES).length};return}const {i,local:p}=manager.resolveTime(clamp(state.time,0,total-.001)),job=jobs[i],phase=phaseAt(p),createP=clamp((p-.37)/(.79-.37)*state.paintSpeed);jobs.forEach((j,n)=>manager.paint(j,n<i?1:n>i?0:(phase==='activating artwork'||phase==='inspecting'||phase==='finishing'?1:createP),{size:state.brush,edge:state.edge,wet:state.wet}));const prev=i===0?-6:jobs[i-1].x,target=job.x-.7;crewRig.root.position.x=lerp(prev-.8,target,ease(clamp(p/.1)));ladder.position.x=lerp(prev-.1,job.x-.1,ease(clamp((p-.06)/.13)));const climb=p<.19?0:p<.29?ease((p-.19)/.1):p<.93?1:p<.97?1-ease((p-.93)/.04):0;crewRig.root.position.y=-2+climb*.5;crewRig.root.scale.setScalar(.64*state.crewScale);ladder.position.y=-1.08;ensureTool(job.method);crewRig.toolPivot.visible=['preparing tool','creating','finishing'].includes(phase);animateTool(currentTool,currentToolName,state.time,phase);animateCrew(crewRig,{phase:phase==='creating'?'painting':phase,progress:createP,time:state.time,motion:state.motion});animateFX(job,phase,createP);
const beat=phase==='creating'?narrativeBeat(job.method,createP):phase==='preparing tool'?METHODS[job.method].narrative[0]:phase;$('#job-chip').textContent=`JOB ${String(i+1).padStart(2,'0')} · ${METHODS[job.method].label.toUpperCase()} · ${phase.toUpperCase()}`;$('#activity').textContent=phase;$('#narrative-beat').textContent=beat.toUpperCase();$('#clock').textContent=`00:${String(Math.floor(state.time)).padStart(2,'0')}`;$('#timeline').value=state.time/total;
if(job.type==='video'&&job.media){const live=job.living&&p>=.93;if(live)job.media.play().catch(()=>{});else job.media.pause();if(live)manager.paint(job,1,{size:state.brush,edge:state.edge,wet:state.wet})}
window.__PYLW_V21__={ready:true,jobs:jobs.length,jobIndex:i,phase,beat,method:job.method,tool:METHODS[job.method].tool,paintProgress:job.progress,videoJobs:jobs.filter(j=>j.type==='video').length,styles:Object.keys(STYLE_PROFILES).length,layout:state.layout,cssLoaded:getComputedStyle($('#authoring-panel')).backgroundColor!=='rgba(0, 0, 0, 0)'}}
function world(name){state.world=name;clearBg();document.body.classList.toggle('world-dark',['dark','urban','manga','game'].includes(name));const c={plaster:[0xd8cdbd,0xb4a691,0xc9beaf],concrete:[0xaaa9a3,0x8f8d86,0xb6b4ae],white:[0xeeeae2,0xd8d4cd,0xf0ede8],dark:[0x3a3938,0x272625,0x343332],mediterranean:[0xd9c9a9,0xbca77e,0xe1d2b7],brick:[0x9b6c59,0x715043,0xaa7a64],urban:[0x6b625d,0x383331,0x514a47],atelier:[0xd3c1a3,0x9e835f,0xc2ae8c],manga:[0xf3f1ec,0xdad7d0,0xf6f4f0],game:[0x20313c,0x17232c,0x172b37],gallery:[0xe9e6df,0xc8c4bb,0xf1eee8],night:[0x202126,0x131417,0x18191e]}[name]||[0xd8cdbd,0xb4a691,0xc9beaf];wallMat.color.set(c[0]);floorMat.color.set(c[1]);scene.background=new THREE.Color(c[2]);scene.fog=new THREE.Fog(c[2],11,24);state.wall='#'+wallMat.color.getHexString();$('#wall-color').value=state.wall;$('#world-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.world===name));persist()}
function lighting(name){const c={studio:[3.2,1.35,0xffe5c4],golden:[4.2,1,0xffc477],overcast:[1.7,1.8,0xe8edf2],dramatic:[5.1,.55,0xffd0a0],neon:[2.3,.7,0x7ecbff]}[name]||[3.2,1.35,0xffe5c4];key.intensity=c[0];hemi.intensity=c[1];key.color.set(c[2]);state.light=c[0];$('#light').value=c[0];$('#out-light').value=c[0].toFixed(2);$('#light-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.light===name));persist()}
$('#asset-upload').onchange=async e=>{const f=[...e.target.files];if(f.length)await ingest(f);e.target.value=''};$('#use-demo').onclick=()=>addDemo(5);$('#add-demo-job').onclick=()=>{manager.create({name:`Demo ${manager.jobs.length+1}`,source:demoCanvas(manager.jobs.length)});$('#onboarding').classList.add('hidden');manager.layout(state.layout);recalc();renderJobs();syncJob()};$('#duplicate-job').onclick=()=>{if(manager.duplicate(state.selected)){state.selected=manager.jobs.length-1;recalc();renderJobs();syncJob()}};$('#delete-job').onclick=()=>{manager.delete(state.selected);state.selected=clamp(state.selected,0,Math.max(0,manager.jobs.length-1));recalc();renderJobs();syncJob()};
$('#method-grid').onclick=e=>{const b=e.target.closest('button[data-method]'),j=manager.jobs[state.selected];if(!b||!j)return;j.method=b.dataset.method;j.reveal=METHODS[j.method].reveal;state.crew=METHODS[j.method].crew;$('#crew-select').value=state.crew;rebuildCrew();renderJobs();syncJob();toast(`${METHODS[j.method].label} · ${METHODS[j.method].tool}`)};
const jobBind=(id,keyName,out,fmt,after)=>$(id)?.addEventListener('input',e=>{const j=manager.jobs[state.selected];if(!j)return;j[keyName]=e.target.valueAsNumber;$(out).value=fmt(j[keyName]);after?.(j);renderJobs()});jobBind('#job-scale','scale','#out-job-scale',v=>v.toFixed(2),j=>manager.layout(state.layout));jobBind('#job-x','xOffset','#out-job-x',v=>v.toFixed(2),()=>manager.layout(state.layout));jobBind('#job-height','height','#out-job-height',v=>v.toFixed(2),()=>manager.layout(state.layout));jobBind('#job-rotation','rotation','#out-job-rotation',v=>`${Math.round(v)}°`,()=>manager.layout(state.layout));jobBind('#job-duration','duration','#out-duration',v=>`${v.toFixed(1)}s`,()=>recalc());$('#asset-fit').onchange=e=>{const j=manager.jobs[state.selected];if(j)j.fit=e.target.value};$('#living-video').onchange=e=>{const j=manager.jobs[state.selected];if(j)j.living=e.target.checked};
$('#layout-select').value=state.layout;$('#layout-select').onchange=e=>{state.layout=e.target.value;manager.layout(state.layout);persist()};$('#background-upload').onchange=async e=>{const f=e.target.files?.[0];if(f)await setBackgroundFile(f);e.target.value=''};$('#clear-background').onclick=()=>world(state.world);
$('#play').onclick=()=>{if(!manager.jobs.length)return toast('Upload content first');state.playing=!state.playing;$('#play').textContent=state.playing?'PAUSE':'PLAY'};$('#restart').onclick=()=>{state.time=0;state.playing=false;$('#play').textContent='PLAY';updateStory()};$('#pace').onchange=e=>state.pace=+e.target.value;$('#timeline').oninput=e=>{state.time=+e.target.value*manager.totalDuration();state.playing=false;$('#play').textContent='PLAY';updateStory()};$('#crew-select').value=state.crew;$('#crew-select').onchange=e=>{state.crew=e.target.value;rebuildCrew();persist()};
function bindRange(id,keyName,out,fmt=v=>Number(v).toFixed(2),after=()=>{}){const el=$(id),o=$(out);if(!el)return;el.value=state[keyName];if(o)o.value=fmt(state[keyName]);el.oninput=e=>{state[keyName]=+e.target.value;if(o)o.value=fmt(state[keyName]);after();persist()}}bindRange('#crew-scale','crewScale','#out-crew-scale');bindRange('#motion','motion','#out-motion');bindRange('#brush-size','brush','#out-brush',v=>String(Math.round(v)));bindRange('#edge-texture','edge','#out-edge');bindRange('#paint-speed','paintSpeed','#out-paint-speed');bindRange('#wet','wet','#out-wet');bindRange('#light','light','#out-light',v=>Number(v).toFixed(2),()=>key.intensity=state.light);bindRange('#exposure','exposure','#out-exposure',v=>Number(v).toFixed(2),()=>renderer.toneMappingExposure=state.exposure);bindRange('#camera-distance','camera','#out-camera',v=>Number(v).toFixed(1),()=>camera.position.z=state.camera);bindRange('#parallax','parallax','#out-parallax');$('#wall-color').value=state.wall;$('#wall-color').oninput=e=>{state.wall=e.target.value;wallMat.color.set(state.wall);persist()};$('#shadows').checked=state.shadows;$('#shadows').onchange=e=>{state.shadows=e.target.checked;renderer.shadowMap.enabled=state.shadows};$('#world-presets').onclick=e=>e.target.dataset.world&&world(e.target.dataset.world);$('#light-presets').onclick=e=>e.target.dataset.light&&lighting(e.target.dataset.light);$('#save-project').onclick=persist;$('#reset-project').onclick=()=>{localStorage.removeItem(STORAGE);location.reload()};$('#capture').onclick=()=>{renderer.render(scene,camera);const a=document.createElement('a');a.download='paint-your-logo-wall-v2-1.png';a.href=renderer.domElement.toDataURL('image/png');a.click()};
function resize(){const r=canvas.parentElement.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas.parentElement);resize();world(state.world);lighting('studio');renderJobs();syncJob();setTimeout(()=>$('#loading').classList.add('hidden'),350);let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing&&manager.jobs.length){state.time+=dt*state.pace;if(state.time>=manager.totalDuration()){state.time=manager.totalDuration()-.001;state.playing=false;$('#play').textContent='PLAY'}}updateStory();renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame)
}
