import * as THREE from 'three';
import {CREW_TEMPLATES,createCrewRig,animateCrew} from './crew-library.js';
import {JobManager,METHODS,demoCanvas} from './v2-jobs.js';
import {STYLE_PROFILES,narrativeBeat} from './v21-style-engine.js';
import {attachTool,animateTool} from './v21-tools.js';
import {activateVideo,resetVideo,mediaSnapshot} from './v22-media.js';
import {saveProjectSnapshot,loadProjectSnapshot,clearProjectSnapshot,serializeJob} from './v22-project-store.js';
const $=s=>document.querySelector(s),clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,ease=t=>t*t*(3-2*t),STORAGE='paint-your-logo-wall-v22-settings';

const BASE=[['approaching',.10],['positioning ladder',.08],['climbing',.12],['preparing tool',.07],['creating',.34],['finishing',.07],['inspecting',.05],['camera look',.035],['wink',.025],['activating artwork',.035],['descending',.07],['relocating ladder',.06]];
function phaseInfo(local,duration){const hold=Math.min(.12,Math.max(.035,.5/Math.max(duration,4))),sum=BASE.reduce((a,x)=>a+x[1],0),scale=(1-hold)/sum;let cursor=0;for(let i=0;i<BASE.length;i++){const [name,w]=BASE[i];if(name==='activating artwork'){const hs=cursor,he=cursor+hold;if(local>=hs&&local<he)return{name:'hold final',p:clamp((local-hs)/hold),start:hs,end:he,activationStart:he};cursor=he}const len=w*scale,start=cursor,end=start+len;if(local>=start&&local<end)return{name,p:clamp((local-start)/len),start,end,activationStart:name==='activating artwork'?start:null};cursor=end}return{name:'relocating ladder',p:1,start:.95,end:1,activationStart:.9}}
function creationProgress(local,duration){let start=0,end=1,cursor=0,hold=Math.min(.12,Math.max(.035,.5/Math.max(duration,4))),sum=BASE.reduce((a,x)=>a+x[1],0),scale=(1-hold)/sum;for(const [name,w] of BASE){if(name==='activating artwork')cursor+=hold;const len=w*scale;if(name==='creating'){start=cursor;end=cursor+len;break}cursor+=len}return clamp((local-start)/(end-start))}
function activationThreshold(duration){let cursor=0,hold=Math.min(.12,Math.max(.035,.5/Math.max(duration,4))),sum=BASE.reduce((a,x)=>a+x[1],0),scale=(1-hold)/sum;for(const [name,w] of BASE){if(name==='activating artwork'){cursor+=hold;return cursor}cursor+=w*scale}return .9}

export function bootV22(){
const state={playing:false,time:0,pace:1,crewScale:1,motion:1,brush:42,edge:.45,paintSpeed:1,wet:.3,world:'plaster',wall:'#d8cdbd',light:3.2,exposure:1,shadows:true,camera:11,parallax:.08,selected:0,layout:'gallery'};try{Object.assign(state,JSON.parse(localStorage.getItem(STORAGE)||'{}'))}catch{}
const canvas=$('#stage'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=state.exposure;
const scene=new THREE.Scene();scene.background=new THREE.Color(0xc9beaf);scene.fog=new THREE.Fog(0xc9beaf,11,24);const camera=new THREE.PerspectiveCamera(38,1,.1,60);camera.position.set(0,.25,state.camera);camera.lookAt(0,.3,0);const hemi=new THREE.HemisphereLight(0xfff7e9,0x6d6255,1.35);scene.add(hemi);const key=new THREE.DirectionalLight(0xffe5c4,state.light);key.position.set(4.5,7.5,8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0xb9d7ff,.75);rim.position.set(-6,3,4);scene.add(rim);
const wallMat=new THREE.MeshStandardMaterial({color:state.wall,roughness:.95});const wall=new THREE.Mesh(new THREE.PlaneGeometry(14,6.6),wallMat);wall.position.set(0,.8,-.55);wall.receiveShadow=true;scene.add(wall);const floorMat=new THREE.MeshStandardMaterial({color:0xb3a794,roughness:.92});const floor=new THREE.Mesh(new THREE.PlaneGeometry(18,9),floorMat);floor.rotation.x=-Math.PI/2;floor.position.set(0,-2.5,2.2);floor.receiveShadow=true;scene.add(floor);const baseboard=new THREE.Mesh(new THREE.BoxGeometry(14,.16,.18),new THREE.MeshStandardMaterial({color:0xb9ac9b,roughness:.82}));baseboard.position.set(0,-2.42,-.25);scene.add(baseboard);
const manager=new JobManager(scene);manager.layoutMode=state.layout;let crewRig=null,currentCrew='',currentTool=null,currentToolName='';
function rebuildCrew(name='aya'){if(crewRig)scene.remove(crewRig.root);currentCrew=name;crewRig=createCrewRig(CREW_TEMPLATES[name]||CREW_TEMPLATES.aya);crewRig.root.scale.setScalar(.64*state.crewScale);scene.add(crewRig.root);currentTool=null;currentToolName=''}rebuildCrew('aya');
const ladder=new THREE.Group(),ladderMat=new THREE.MeshStandardMaterial({color:0x8f7d67,roughness:.5,metalness:.2});for(const x of [-.34,.34]){const r=new THREE.Mesh(new THREE.BoxGeometry(.09,2.8,.09),ladderMat);r.position.x=x;r.rotation.z=x<0?-.08:.08;r.castShadow=true;ladder.add(r)}for(let y=-1.08;y<1.18;y+=.38){const r=new THREE.Mesh(new THREE.BoxGeometry(.64,.055,.07),ladderMat);r.position.y=y;r.castShadow=true;ladder.add(r)}scene.add(ladder);
const fxGroup=new THREE.Group();scene.add(fxGroup);for(let i=0;i<50;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.012,6,4),new THREE.MeshBasicMaterial({color:0xffe2a6,transparent:true,opacity:.7}));p.visible=false;fxGroup.add(p)}
let customBg=null,customBgMedia=null;function clearBg(){if(customBg?.isTexture)customBg.dispose();if(customBgMedia?.pause){customBgMedia.pause();URL.revokeObjectURL(customBgMedia.src)}customBg=null;customBgMedia=null}
async function setBackgroundFile(file){clearBg();if(file.type.startsWith('video/')){const v=document.createElement('video');v.muted=true;v.loop=true;v.playsInline=true;v.src=URL.createObjectURL(file);v.load();await new Promise((res,rej)=>{v.oncanplay=res;v.onerror=rej});await v.play().catch(()=>{});customBgMedia=v;customBg=new THREE.VideoTexture(v);customBg.colorSpace=THREE.SRGBColorSpace}else{const img=new Image();img.src=URL.createObjectURL(file);await img.decode();customBg=new THREE.Texture(img);customBg.needsUpdate=true;customBg.colorSpace=THREE.SRGBColorSpace;URL.revokeObjectURL(img.src)}scene.background=customBg;scene.fog=null;$('#background-status').textContent=`${file.name} · custom world active`}
function persistSettings(){localStorage.setItem(STORAGE,JSON.stringify({...state,time:0,playing:false}))}function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function ensureTool(method){const name=METHODS[method]?.tool||'brush';if(name!==currentToolName){currentToolName=name;currentTool=attachTool(crewRig.toolPivot,name)}}
function toolTarget(job,p){const rows=7,row=Math.min(rows-1,Math.floor(p*rows)),rp=(p*rows)%1,rev=row%2===1;return{x:job.mesh.position.x+((rev?1-rp:rp)-.5)*1.72*job.mesh.scale.x,y:job.mesh.position.y+(.37-row/(rows-1)*.74)*job.mesh.scale.y}}
function aimWorkingArm(job,p){if(!crewRig||!['creating','finishing'].includes(window.__PYLW_PHASE__))return;const target=toolTarget(job,p),shoulder=new THREE.Vector3();crewRig.shoulderR.getWorldPosition(shoulder);const dx=target.x-shoulder.x,dy=target.y-shoulder.y,l1=crewRig.spec.upper,l2=crewRig.spec.lower,d=clamp(Math.hypot(dx,dy),.1,l1+l2-.02),a=Math.atan2(dy,dx),c1=Math.acos(clamp((l1*l1+d*d-l2*l2)/(2*l1*d),-1,1)),c2=Math.acos(clamp((l1*l1+l2*l2-d*d)/(2*l1*l2),-1,1));crewRig.shoulderR.rotation.z=a-c1;crewRig.elbowR.rotation.z=Math.PI-c2}
function animateFX(job,phase){fxGroup.children.forEach(p=>p.visible=false);if(phase!=='creating'||!['spray','expressionist','charcoal','digital'].includes(job.method))return;const amount=job.method==='spray'?30:job.method==='expressionist'?20:12;for(let i=0;i<amount;i++){const p=fxGroup.children[i],r=(i*17.17+state.time*24)%1,a=i*2.399;p.visible=true;p.material.color.set(job.method==='digital'?0x73caff:job.method==='charcoal'?0x4a4540:0xff8b52);p.position.set(job.x-.15+Math.cos(a)*r*.48,job.mesh.position.y+Math.sin(a)*r*.28+.1,0.02+r*.2);p.scale.setScalar(.5+r*1.6);p.material.opacity=.25+(1-r)*.55}}

function renderJobs(){const list=$('#job-list');list.innerHTML='';manager.jobs.forEach((j,i)=>{const row=document.createElement('div');row.className='job-row'+(i===state.selected?' active':'');const status=j.type==='video'?` · ${String(j.mediaStatus||'ready').toUpperCase()}`:'';row.innerHTML=`<span class="job-index">${String(i+1).padStart(2,'0')}</span><div class="job-meta"><b>${j.name}</b><span>${j.type} · ${METHODS[j.method].label}${status}</span></div><div class="job-actions"><button data-up>↑</button><button data-down>↓</button></div>`;row.onclick=e=>{if(e.target.dataset.up!==undefined){e.stopPropagation();state.selected=manager.move(i,-1);renderJobs();syncJob();return}if(e.target.dataset.down!==undefined){e.stopPropagation();state.selected=manager.move(i,1);renderJobs();syncJob();return}state.selected=i;renderJobs();syncJob()};list.appendChild(row)});$('#job-count').textContent=`${manager.jobs.length} Job${manager.jobs.length===1?'':'s'}`;const vids=manager.jobs.filter(j=>j.type==='video');$('#asset-status').textContent=manager.jobs.length?`${manager.jobs.length} jobs · ${vids.length} video (${vids.filter(v=>v.mediaStatus!=='error').length} ready) · ${manager.jobs.filter(j=>j.type==='image').length} image`:'Upload content first. Every asset becomes a configurable creative job.'}
function syncJob(){const j=manager.jobs[state.selected],set=(id,v,out,txt)=>{if(!$(id))return;$(id).disabled=!j;if(j&&v!==undefined)$(id).value=v;if(j&&out)$(out).value=txt??v};$('#selected-item-label').textContent=j?`Job ${String(state.selected+1).padStart(2,'0')}`:'None';set('#job-scale',j?.scale,'#out-job-scale',j?.scale?.toFixed(2));set('#job-x',j?.xOffset,'#out-job-x',j?.xOffset?.toFixed(2));set('#job-height',j?.height,'#out-job-height',j?.height?.toFixed(2));set('#job-rotation',j?.rotation,'#out-job-rotation',j?`${j.rotation}°`:null);set('#job-duration',j?.duration,'#out-duration',j?`${j.duration.toFixed(1)}s`:null);set('#asset-fit',j?.fit);if($('#living-video')){$('#living-video').disabled=!j||j.type!=='video';$('#living-video').checked=!!j?.living}$('#method-grid').querySelectorAll('button').forEach(b=>b.classList.toggle('active',j?.method===b.dataset.method));if(j){$('#crew-select').value=j.crew||METHODS[j.method].crew;$('#style-summary').textContent=`${METHODS[j.method].label} · ${METHODS[j.method].narrative.join(' → ')}`;$('#media-job-status').textContent=j.type==='video'?`VIDEO · ${j.mediaStatus.toUpperCase()} · poster ready · ${j.activated?'LIVE':'waiting activation'}`:'IMAGE · ready'}else{$('#style-summary').textContent='Select a job';$('#media-job-status').textContent='No selected media'}}
function recalc(){state.time=clamp(state.time,0,Math.max(.001,manager.totalDuration()-.001))}
async function ingest(files){let ok=0,fail=0;for(const f of files){try{await manager.fromFile(f);ok++}catch(error){fail++;console.error(error);toast(`Could not load ${f.name}`)}}state.selected=Math.max(0,manager.jobs.length-ok);$('#onboarding').classList.toggle('hidden',manager.jobs.length>0);manager.layout(state.layout);recalc();renderJobs();syncJob();toast(`${ok} asset${ok===1?'':'s'} ready${fail?` · ${fail} failed`:''}`)}
function addDemo(n=5){for(let i=0;i<n;i++){const j=manager.create({name:['North','Field','Mono','Studio','Signal'][i%5],source:demoCanvas(i)});j.method=['brush','spray','ink','expressionist','digital'][i%5];j.reveal=METHODS[j.method].reveal;j.crew=METHODS[j.method].crew}$('#onboarding').classList.add('hidden');manager.layout(state.layout);recalc();renderJobs();syncJob()}

async function saveProject(){await saveProjectSnapshot({version:'2.2',state:{...state,time:0,playing:false},jobs:manager.jobs.map(serializeJob)});$('#status').textContent='SAVED · configuration + uploaded media';toast('Project saved with media')}
async function loadProject(){const snap=await loadProjectSnapshot();if(!snap){toast('No saved project');return}manager.clear();Object.assign(state,snap.state||{});for(const cfg of snap.jobs||[]){try{await manager.restore(cfg)}catch(e){console.error(e)}}state.selected=0;manager.layout(state.layout);world(state.world,false);renderJobs();syncJob();recalc();$('#onboarding').classList.toggle('hidden',manager.jobs.length>0);$('#status').textContent=`LOADED · ${manager.jobs.length} jobs`;toast('Saved project loaded')}
async function resetProject(){state.playing=false;state.time=0;manager.clear();await clearProjectSnapshot();state.selected=0;renderJobs();syncJob();$('#onboarding').classList.remove('hidden');$('#status').textContent='EMPTY PROJECT · upload content';toast('Project cleared')}
function restartStory(){state.playing=false;state.time=0;manager.resetPlayback();manager.jobs.forEach(j=>manager.paint(j,0,{size:state.brush,edge:state.edge,wet:state.wet}));$('#play').textContent='PLAY STORY';toast('Story restarted · project kept')}
function restartSelected(){const j=manager.jobs[state.selected];if(!j)return;j.progress=0;if(j.type==='video')resetVideo(j);manager.paint(j,0,{size:state.brush,edge:state.edge,wet:state.wet});toast(`Job ${state.selected+1} restarted`)}

function world(name,save=true){state.world=name;clearBg();document.body.classList.toggle('world-dark',['dark','urban','manga','game','night'].includes(name));const c={plaster:[0xd8cdbd,0xb4a691,0xc9beaf],concrete:[0xaaa9a3,0x8f8d86,0xb6b4ae],white:[0xeeeae2,0xd8d4cd,0xf0ede8],dark:[0x3a3938,0x272625,0x343332],mediterranean:[0xd9c9a9,0xbca77e,0xe1d2b7],brick:[0x9b6c59,0x715043,0xaa7a64],urban:[0x6b625d,0x383331,0x514a47],atelier:[0xd3c1a3,0x9e835f,0xc2ae8c],manga:[0xf3f1ec,0xdad7d0,0xf6f4f0],game:[0x20313c,0x17232c,0x172b37],gallery:[0xe9e6df,0xc8c4bb,0xf1eee8],night:[0x202126,0x131417,0x18191e]}[name]||[0xd8cdbd,0xb4a691,0xc9beaf];wallMat.color.set(c[0]);floorMat.color.set(c[1]);scene.background=new THREE.Color(c[2]);scene.fog=new THREE.Fog(c[2],11,24);state.wall='#'+wallMat.color.getHexString();if($('#wall-color'))$('#wall-color').value=state.wall;$('#world-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.world===name));if(save)persistSettings()}
function lighting(name){const c={studio:[3.2,1.35,0xffe5c4],golden:[4.2,1,0xffc477],overcast:[1.7,1.8,0xe8edf2],dramatic:[5.1,.55,0xffd0a0],neon:[2.3,.7,0x7ecbff]}[name]||[3.2,1.35,0xffe5c4];key.intensity=c[0];hemi.intensity=c[1];key.color.set(c[2]);state.light=c[0];$('#light').value=c[0];$('#out-light').value=c[0].toFixed(2);$('#light-presets').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.light===name));persistSettings()}

let activationLocks=new Set();function ensureActivated(j){if(j.type!=='video'||!j.living||j.activated||activationLocks.has(j.id))return;activationLocks.add(j.id);activateVideo(j).then(()=>{activationLocks.delete(j.id);renderJobs();syncJob()})}
function updateStory(){const jobs=manager.jobs,total=manager.totalDuration();if(!jobs.length){$('#job-chip').textContent='WAITING FOR CONTENT';$('#activity').textContent='upload content';$('#narrative-beat').textContent='STEP 01 · Upload images or videos';window.__PYLW_V22__={ready:true,jobs:0,cssLoaded:true};return}const resolved=manager.resolveTime(clamp(state.time,0,total-.001)),i=resolved.i,local=resolved.local,job=jobs[i],info=phaseInfo(local,job.duration),phase=info.name,createP=creationProgress(local,job.duration);window.__PYLW_PHASE__=phase;
for(let n=0;n<jobs.length;n++){const j=jobs[n];if(n<i){manager.paint(j,1,{size:state.brush,edge:state.edge,wet:state.wet});if(j.type==='video'&&j.living)ensureActivated(j)}else if(n>i)manager.paint(j,0,{size:state.brush,edge:state.edge,wet:state.wet});else{const p=['finishing','inspecting','camera look','wink','hold final','activating artwork','descending','relocating ladder'].includes(phase)?1:createP;manager.paint(j,p,{size:state.brush,edge:state.edge,wet:state.wet})}}
if(job.type==='video'&&job.living&&local>=activationThreshold(job.duration))ensureActivated(job);
const prevX=i===0?-6:jobs[i-1].x-.1,targetLadder=job.x-.1,nextLadder=(jobs[i+1]?.x??job.x)-.1,targetRoot=job.x-.72,baseY=-2,rise=clamp(.85+Math.max(0,job.mesh.position.y)*.22,.85,1.55);let rootX=targetRoot,rootY=baseY,ladderX=targetLadder,ladderTilt=0;
if(phase==='approaching'){rootX=lerp(prevX-.7,targetRoot,info.p);ladderX=prevX}else if(phase==='positioning ladder'){rootX=targetRoot;ladderX=lerp(prevX,targetLadder,ease(info.p));ladderTilt=Math.sin(info.p*Math.PI)*.12}else if(phase==='climbing'){rootY=baseY+rise*ease(info.p)}else if(['preparing tool','creating','finishing','inspecting','camera look','wink','hold final','activating artwork'].includes(phase)){rootY=baseY+rise}else if(phase==='descending'){rootY=baseY+rise*(1-ease(info.p))}else if(phase==='relocating ladder'){rootX=lerp(targetRoot,nextLadder-.6,ease(info.p));ladderX=lerp(targetLadder,nextLadder,ease(info.p));ladderTilt=Math.sin(info.p*Math.PI)*.10}
crewRig.root.position.x=rootX;crewRig.root.position.y=rootY;crewRig.root.scale.setScalar(.64*state.crewScale);ladder.position.set(ladderX,-1.08,0);ladder.rotation.z=ladderTilt;
const desiredCrew=job.crew||METHODS[job.method].crew;if(desiredCrew!==currentCrew){rebuildCrew(desiredCrew);crewRig.root.position.set(rootX,rootY,0)}ensureTool(job.method);crewRig.toolPivot.visible=['preparing tool','creating','finishing'].includes(phase);animateTool(currentTool,currentToolName,state.time,phase);animateCrew(crewRig,{phase,progress:createP,phaseProgress:info.p,time:state.time,motion:state.motion});aimWorkingArm(job,createP);animateFX(job,phase);
const beat=phase==='creating'?narrativeBeat(job.method,createP):phase==='preparing tool'?METHODS[job.method].narrative[0]:phase==='camera look'?'LOOK TO CAMERA':phase==='wink'?'WINK':phase==='hold final'?'FINAL ARTWORK · HOLD 0.5s':phase;$('#job-chip').textContent=`JOB ${String(i+1).padStart(2,'0')} · ${METHODS[job.method].label.toUpperCase()} · ${phase.toUpperCase()}`;$('#activity').textContent=phase;$('#narrative-beat').textContent=String(beat).toUpperCase();$('#clock').textContent=`${String(Math.floor(state.time/60)).padStart(2,'0')}:${String(Math.floor(state.time%60)).padStart(2,'0')}`;$('#timeline').value=state.time/total;
const videos=jobs.filter(j=>j.type==='video');window.__PYLW_V22__={ready:true,jobs:jobs.length,jobIndex:i,phase,phaseProgress:info.p,beat,method:job.method,crew:job.crew,tool:METHODS[job.method].tool,paintProgress:job.progress,videoJobs:videos.length,videos:videos.map(mediaSnapshot),styles:Object.keys(STYLE_PROFILES).length,layout:state.layout,cssLoaded:getComputedStyle($('#authoring-panel')).backgroundColor!=='rgba(0, 0, 0, 0)',ladderX,rootY,rise}}

$('#asset-upload').onchange=async e=>{const f=[...e.target.files];if(f.length)await ingest(f);e.target.value=''};$('#use-demo').onclick=()=>addDemo(5);$('#add-demo-job').onclick=()=>{const j=manager.create({name:`Demo ${manager.jobs.length+1}`,source:demoCanvas(manager.jobs.length)});j.crew=METHODS[j.method].crew;$('#onboarding').classList.add('hidden');manager.layout(state.layout);recalc();renderJobs();syncJob()};$('#duplicate-job').onclick=async()=>{if(await manager.duplicate(state.selected)){state.selected=manager.jobs.length-1;recalc();renderJobs();syncJob();toast('Job duplicated')}};$('#delete-job').onclick=()=>{manager.delete(state.selected);state.selected=clamp(state.selected,0,Math.max(0,manager.jobs.length-1));recalc();renderJobs();syncJob()};
$('#method-grid').onclick=e=>{const b=e.target.closest('[data-method]'),j=manager.jobs[state.selected];if(!b||!j)return;j.method=b.dataset.method;j.reveal=METHODS[j.method].reveal;if(!j.crew||j.crew===currentCrew)j.crew=METHODS[j.method].crew;renderJobs();syncJob()};$('#crew-select').onchange=e=>{const j=manager.jobs[state.selected];if(!j)return;j.crew=e.target.value;syncJob()};
[['#job-scale','scale',v=>+v],['#job-x','xOffset',v=>+v],['#job-height','height',v=>+v],['#job-rotation','rotation',v=>+v],['#job-duration','duration',v=>+v],['#asset-fit','fit',v=>v]].forEach(([id,k,cast])=>$(id).oninput=e=>{const j=manager.jobs[state.selected];if(!j)return;j[k]=cast(e.target.value);manager.layout(state.layout);recalc();syncJob()});$('#living-video').onchange=e=>{const j=manager.jobs[state.selected];if(j)j.living=e.target.checked};$('#layout-select').onchange=e=>{state.layout=e.target.value;manager.layout(state.layout);persistSettings()};
[['#brush-size','brush','#out-brush',0],['#edge-texture','edge','#out-edge',2],['#paint-speed','paintSpeed','#out-paint-speed',2],['#wet','wet','#out-wet',2],['#crew-scale','crewScale','#out-crew-scale',2],['#motion','motion','#out-motion',2],['#light','light','#out-light',2],['#exposure','exposure','#out-exposure',2],['#camera-distance','camera','#out-camera',1],['#parallax','parallax','#out-parallax',2]].forEach(([id,k,out,d])=>$(id).oninput=e=>{state[k]=+e.target.value;$(out).value=state[k].toFixed(d);if(k==='light')key.intensity=state[k];if(k==='exposure')renderer.toneMappingExposure=state[k];if(k==='camera')camera.position.z=state[k];persistSettings()});
$('#world-presets').onclick=e=>{const b=e.target.closest('[data-world]');if(b)world(b.dataset.world)};$('#light-presets').onclick=e=>{const b=e.target.closest('[data-light]');if(b)lighting(b.dataset.light)};$('#background-upload').onchange=async e=>{const f=e.target.files?.[0];if(f)await setBackgroundFile(f);e.target.value=''};$('#clear-background').onclick=()=>world(state.world);$('#wall-color').oninput=e=>{state.wall=e.target.value;wallMat.color.set(state.wall);persistSettings()};$('#shadows').onchange=e=>{state.shadows=e.target.checked;renderer.shadowMap.enabled=state.shadows;persistSettings()};
$('#play').onclick=()=>{state.playing=!state.playing;$('#play').textContent=state.playing?'PAUSE':'PLAY STORY'};$('#restart').onclick=restartStory;$('#restart-job').onclick=restartSelected;$('#pace').onchange=e=>state.pace=+e.target.value;$('#timeline').oninput=e=>{state.playing=false;state.time=+e.target.value*manager.totalDuration();$('#play').textContent='PLAY STORY'};$('#save-project').onclick=saveProject;$('#load-project').onclick=loadProject;$('#reset-project').onclick=resetProject;$('#capture').onclick=()=>{const a=document.createElement('a');a.href=renderer.domElement.toDataURL('image/png');a.download='paint-your-logo-wall-v22.png';a.click()};
function resize(){const r=canvas.parentElement.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}window.addEventListener('resize',resize);resize();world(state.world,false);manager.layout(state.layout);renderJobs();syncJob();$('#loading').classList.add('hidden');
let last=performance.now();function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(state.playing&&manager.jobs.length){state.time+=dt*state.pace;if(state.time>=manager.totalDuration()){state.time=manager.totalDuration()-.001;state.playing=false;$('#play').textContent='PLAY STORY'}}updateStory();camera.position.x=Math.sin(now*.00023)*state.parallax;camera.lookAt(0,.3,0);renderer.render(scene,camera);requestAnimationFrame(frame)}requestAnimationFrame(frame);
}
